const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'),ctx=canvas.getContext('2d'),map=$('#map'),mctx=map.getContext('2d');
const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
let W,H,dpr=Math.min(devicePixelRatio||1,2),last=0,started=false,panel=null;
const state={level:1,xp:0,xpNext:100,hp:120,maxHp:120,energy:100,maxEnergy:100,silver:180,favor:0,
  player:{x:0,y:0,r:18,speed:210,target:null,angle:0,flash:0}, keys:{}, quest:0, faction:null,guild:null,
  mastery:{combat:8,gather:0,craft:0}, cool:{cleave:0,dash:0,mend:0},
  inv:{wood:0,ore:0,hide:0,herb:1,bronze:0,plank:0,sword:1,buckler:0,potion:2},
  equipped:{weapon:'sword',offhand:null}, enemies:[], nodes:[], particles:[],floaters:[]};
const items={wood:{name:'Olivewood',icon:'♣',rarity:1},ore:{name:'Bronze Ore',icon:'◆',rarity:1},hide:{name:'Boar Hide',icon:'◒',rarity:1},herb:{name:'Moly Herb',icon:'❧',rarity:2},bronze:{name:'Bronze Ingot',icon:'▰',rarity:2},plank:{name:'Olive Plank',icon:'▥',rarity:2},sword:{name:'Worn Xiphos',icon:'†',rarity:1},buckler:{name:'Gorgon Buckler',icon:'◉',rarity:3},potion:{name:'Ambrosia',icon:'⚱',rarity:2}};
const recipes=[
 {id:'plank',name:'Olive Plank',icon:'▥',cost:{wood:2},out:1,kind:'Refine'},
 {id:'bronze',name:'Bronze Ingot',icon:'▰',cost:{ore:2},out:1,kind:'Refine'},
 {id:'sword',name:'Bronze Xiphos',icon:'†',cost:{bronze:3,wood:1},out:1,kind:'Weapon'},
 {id:'buckler',name:'Gorgon Buckler',icon:'◉',cost:{bronze:2,wood:2},out:1,kind:'Off-hand'},
 {id:'potion',name:'Ambrosia',icon:'⚱',cost:{herb:2},out:2,kind:'Consumable'},
 {id:'spear',name:'Ash Spear',icon:'⚚',cost:{plank:3,bronze:2},out:1,kind:'Weapon',locked:true}
];
function resize(){W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);state.player.x||Object.assign(state.player,{x:W/2,y:H/2});}
addEventListener('resize',resize);resize();
function seedWorld(){
 const types=['wood','wood','ore','wood','ore','herb','wood','ore','herb'];
 for(let i=0;i<36;i++){let a=Math.random()*TAU,r=140+Math.random()*Math.min(W,H)*.62;state.nodes.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,type:types[i%types.length],alive:true,t:0});}
 for(let i=0;i<8;i++) spawnEnemy();
}
function spawnEnemy(){let a=Math.random()*TAU,r=300+Math.random()*260;state.enemies.push({x:W/2+Math.cos(a)*r,y:H/2+Math.sin(a)*r,hp:55,maxHp:55,r:20,attack:0,flash:0,dead:false,name:'Ash Wretch'});}
seedWorld();
function enter(){if(started)return;started=true;$('#boot').style.opacity=0;setTimeout(()=>$('#boot').remove(),1000);$('#game').classList.remove('hidden');toast('THE THREAD BEGINS');requestAnimationFrame(loop)}
$('#enterBtn').onclick=enter;$('#boot').onclick=enter;
addEventListener('keydown',e=>{state.keys[e.key.toLowerCase()]=true;if(['i','c','p','f','g'].includes(e.key.toLowerCase())){let m={i:'inventory',c:'forge',p:'mastery',f:'factions',g:'guild'}[e.key.toLowerCase()];togglePanel(m)}if(e.key==='Escape')closePanel();if(e.key.toLowerCase()==='e')interact();if('124'.includes(e.key))useAbility({'1':'cleave','2':'dash','4':'mend'}[e.key])});
addEventListener('keyup',e=>state.keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointerdown',e=>{let enemy=nearest(state.enemies.filter(x=>!x.dead),e.clientX,e.clientY,35);if(enemy){state.player.target=null;attack(enemy)}else state.player.target={x:e.clientX,y:e.clientY}});
$$('[data-panel]').forEach(b=>b.onclick=()=>togglePanel(b.dataset.panel));$('#closePanel').onclick=closePanel;$('#respawnBtn').onclick=respawn;
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}function nearest(arr,x,y,max=1e9){let best=null,d=max;for(let o of arr){let q=Math.hypot(o.x-x,o.y-y);if(q<d){best=o;d=q}}return best}
function update(dt){
 let p=state.player,dx=(state.keys.d?1:0)-(state.keys.a?1:0),dy=(state.keys.s?1:0)-(state.keys.w?1:0);if(dx||dy){let l=Math.hypot(dx,dy);dx/=l;dy/=l;p.target=null;p.angle=Math.atan2(dy,dx)}else if(p.target){let d=dist(p,p.target);if(d>5){dx=(p.target.x-p.x)/d;dy=(p.target.y-p.y)/d;p.angle=Math.atan2(dy,dx)}else p.target=null}p.x=clamp(p.x+dx*p.speed*dt,30,W-30);p.y=clamp(p.y+dy*p.speed*dt,90,H-40);p.flash=Math.max(0,p.flash-dt);
 for(let k in state.cool)state.cool[k]=Math.max(0,state.cool[k]-dt);state.energy=clamp(state.energy+8*dt,0,state.maxEnergy);
 for(let n of state.nodes){if(!n.alive){n.t-=dt;if(n.t<=0)n.alive=true}}
 for(let e of state.enemies){if(e.dead)continue;e.flash=Math.max(0,e.flash-dt);let d=dist(e,p);if(d<200){let vx=(p.x-e.x)/d,vy=(p.y-e.y)/d;if(d>48){e.x+=vx*55*dt;e.y+=vy*55*dt}e.attack-=dt;if(d<52&&e.attack<=0){damagePlayer(11);e.attack=1.3}}}
 state.particles=state.particles.filter(q=>(q.life-=dt)>0);for(let q of state.particles){q.x+=q.vx*dt;q.y+=q.vy*dt}
 state.floaters=state.floaters.filter(q=>(q.life-=dt)>0);for(let q of state.floaters)q.y-=25*dt;updateUI();
}
function draw(){
 let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,'#24332e');g.addColorStop(.5,'#51422f');g.addColorStop(1,'#261f31');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);
 ctx.globalAlpha=.18;for(let x=0;x<W;x+=80)for(let y=0;y<H;y+=70){ctx.fillStyle=((x/80+y/70)%2?'#786b48':'#243829');ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+55,y-20);ctx.lineTo(x+85,y+35);ctx.lineTo(x+20,y+60);ctx.fill()}ctx.globalAlpha=1;
 drawRuins();for(let n of state.nodes)if(n.alive)drawNode(n);for(let e of state.enemies)if(!e.dead)drawEnemy(e);drawPlayer();
 for(let q of state.particles){ctx.globalAlpha=q.life;ctx.fillStyle=q.color;ctx.fillRect(q.x,q.y,q.size,q.size)}ctx.globalAlpha=1;ctx.textAlign='center';ctx.font='bold 12px Inter';for(let f of state.floaters){ctx.globalAlpha=f.life;ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;drawMap();
}
function drawRuins(){ctx.save();ctx.translate(W/2,H/2);ctx.fillStyle='#392f34';ctx.strokeStyle='#7c6949';ctx.lineWidth=3;for(let i=0;i<8;i++){let a=i/8*TAU,x=Math.cos(a)*110,y=Math.sin(a)*80;ctx.save();ctx.translate(x,y);ctx.rotate(a);ctx.fillRect(-13,-30,26,60);ctx.strokeRect(-13,-30,26,60);ctx.restore()}ctx.beginPath();ctx.ellipse(0,0,80,50,0,0,TAU);ctx.stroke();ctx.fillStyle='#9a744b';ctx.beginPath();ctx.arc(0,0,11,0,TAU);ctx.fill();ctx.restore()}
function drawNode(n){ctx.save();ctx.translate(n.x,n.y);if(n.type==='wood'){ctx.fillStyle='#4b342c';ctx.fillRect(-5,-8,10,28);ctx.fillStyle='#41583b';for(let i=0;i<3;i++){ctx.beginPath();ctx.arc((i-1)*10,-12-(i%2)*7,17,0,TAU);ctx.fill()}}else if(n.type==='ore'){ctx.fillStyle='#84654c';for(let i=0;i<3;i++){ctx.beginPath();ctx.moveTo(-22+i*14,15);ctx.lineTo(-12+i*14,-16);ctx.lineTo(5+i*10,13);ctx.fill()}}else{ctx.strokeStyle='#5c7a4e';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(0,15);ctx.lineTo(0,-12);ctx.stroke();ctx.fillStyle='#a9a065';ctx.beginPath();ctx.arc(0,-15,8,0,TAU);ctx.fill()}ctx.restore()}
function drawEnemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.flash?'#efe1c2':'#574052';ctx.beginPath();ctx.moveTo(0,-25);ctx.lineTo(18,-5);ctx.lineTo(14,22);ctx.lineTo(-14,22);ctx.lineTo(-18,-5);ctx.fill();ctx.fillStyle='#b16144';ctx.fillRect(-8,-10,5,3);ctx.fillRect(3,-10,5,3);ctx.fillStyle='#170f18';ctx.fillRect(-22,-34,44,5);ctx.fillStyle='#9c493e';ctx.fillRect(-22,-34,44*e.hp/e.maxHp,5);ctx.restore()}
function drawPlayer(){let p=state.player;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();ctx.ellipse(0,15,24,10,0,0,TAU);ctx.fill();ctx.fillStyle=p.flash?'#fff':'#d2b89b';ctx.beginPath();ctx.arc(0,-10,9,0,TAU);ctx.fill();ctx.fillStyle='#6c3e42';ctx.beginPath();ctx.moveTo(-13,-3);ctx.lineTo(15,-4);ctx.lineTo(12,22);ctx.lineTo(-10,20);ctx.fill();ctx.strokeStyle='#d9bd70';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(28,-14);ctx.stroke();ctx.restore()}
function drawMap(){mctx.fillStyle='#171922';mctx.fillRect(0,0,150,150);mctx.fillStyle='#304638';for(let i=0;i<18;i++){mctx.beginPath();mctx.arc((i*47)%150,(i*83)%150,10,0,TAU);mctx.fill()}mctx.strokeStyle='#8d754d';mctx.beginPath();mctx.arc(75,75,18,0,TAU);mctx.stroke();mctx.fillStyle='#e2c66e';mctx.beginPath();mctx.arc(75+(state.player.x-W/2)/W*75,75+(state.player.y-H/2)/H*75,3,0,TAU);mctx.fill()}
function interact(){let n=nearest(state.nodes.filter(n=>n.alive),state.player.x,state.player.y,62);if(n)gather(n)}
function gather(n){n.alive=false;n.t=12;state.inv[n.type]++;state.mastery.gather+=8;gainXp(12);loot(`+1 ${items[n.type].name}`);burst(n.x,n.y,n.type==='ore'?'#b98d64':'#829b62');checkQuest();}
function attack(e){let p=state.player,d=dist(p,e);if(d>70){p.target={x:e.x,y:e.y};return}p.angle=Math.atan2(e.y-p.y,e.x-p.x);hit(e,18);}
function hit(e,dmg){e.hp-=dmg;e.flash=.12;state.floaters.push({x:e.x,y:e.y-30,text:`${dmg}`,color:'#efd08b',life:1});burst(e.x,e.y,'#b75946');if(e.hp<=0){e.dead=true;gainXp(28);state.silver+=12+Math.floor(Math.random()*9);state.mastery.combat+=10;loot('+ spoils · drachma');setTimeout(spawnEnemy,4500)}}
function useAbility(id){if(state.cool[id]>0)return;if(id==='cleave'&&state.energy>=20){state.energy-=20;state.cool[id]=3;for(let e of state.enemies)if(!e.dead&&dist(e,state.player)<105)hit(e,32);burst(state.player.x,state.player.y,'#d2a94e',22)}if(id==='dash'&&state.energy>=16){state.energy-=16;state.cool[id]=5;state.player.x=clamp(state.player.x+Math.cos(state.player.angle)*120,30,W-30);state.player.y=clamp(state.player.y+Math.sin(state.player.angle)*120,90,H-40);burst(state.player.x,state.player.y,'#698fa9',16)}if(id==='mend'&&state.inv.potion>0){state.inv.potion--;state.cool[id]=8;state.hp=clamp(state.hp+48,0,state.maxHp);toast('AMBROSIA RESTORES YOU');burst(state.player.x,state.player.y,'#77a46c',18)}}
function damagePlayer(n){if(state.hp<=0)return;state.hp-=n;state.player.flash=.15;state.floaters.push({x:state.player.x,y:state.player.y-35,text:`-${n}`,color:'#e16b55',life:1});if(state.hp<=0)$('#deathScreen').classList.remove('hidden')}
function respawn(){state.hp=state.maxHp;Object.assign(state.player,{x:W/2,y:H/2,target:null});$('#deathScreen').classList.add('hidden');toast('THE FATES REWEAVE YOUR THREAD')}
function gainXp(n){state.xp+=n;while(state.xp>=state.xpNext){state.xp-=state.xpNext;state.level++;state.xpNext=Math.floor(state.xpNext*1.35);state.maxHp+=12;state.hp=state.maxHp;state.favor+=1;toast(`RENOWN ${state.level} · THE GODS TAKE NOTICE`)}}
function burst(x,y,color,count=10){for(let i=0;i<count;i++){let a=Math.random()*TAU,s=30+Math.random()*90;state.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,size:2+Math.random()*3,color,life:.5+Math.random()*.4})}}
function checkQuest(){if(state.quest===0&&state.inv.wood>=3&&state.inv.ore>=2){state.quest=1;state.silver+=75;state.favor++;toast('THREAD COMPLETE · +75 DRACHMA');$('#questTitle').textContent='The First Forging';$('#questText').textContent='Refine an olive plank and a bronze ingot.'}if(state.quest===1&&state.inv.plank>=1&&state.inv.bronze>=1){state.quest=2;toast('NEW PATH UNLOCKED · CRAFT A BUCKLER');$('#questTitle').textContent='An Heirloom Reborn';$('#questText').textContent='Craft a Gorgon Buckler at the forge.'}if(state.quest===2&&state.inv.buckler>=1){state.quest=3;state.favor+=3;toast('THREAD COMPLETE · GORGON OATH EARNED');$('#questTitle').textContent='Beyond the Gloam';$('#questText').textContent='Reach Renown 3 and choose a divine faction.'}}
function updateUI(){let n=nearest(state.nodes.filter(n=>n.alive),state.player.x,state.player.y,62);$('#prompt').classList.toggle('hidden',!n);if(n)$('#prompt span').textContent='Gather '+items[n.type].name;$('#hpBar').style.width=state.hp/state.maxHp*100+'%';$('#energyBar').style.width=state.energy/state.maxEnergy*100+'%';$('#hpText').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('#energyText').textContent=`${Math.ceil(state.energy)} / ${state.maxEnergy}`;$('#xpBar').style.width=state.xp/state.xpNext*100+'%';$('#levelBadge').textContent=state.level;$('#silver').textContent=state.silver;$('#favor').textContent=state.favor;let qp=state.quest===0?Math.min(1,(Math.min(state.inv.wood,3)+Math.min(state.inv.ore,2))/5):state.quest===1?Math.min(1,(state.inv.plank+state.inv.bronze)/2):state.quest===2?(state.inv.buckler?1:0):Math.min(1,state.level/3);$('#questProgress').innerHTML=`<i style="width:${qp*100}%"></i>`;$$('.skill[data-ability]').forEach(b=>{let c=state.cool[b.dataset.ability];b.querySelector('.cooldown').style.transform=`scaleY(${Math.min(1,c/({cleave:3,dash:5,mend:8}[b.dataset.ability]))})`})}
function loot(t){let d=document.createElement('div');d.className='loot';d.textContent=t;$('#lootFeed').append(d);setTimeout(()=>d.remove(),3000)}function toast(t){let d=document.createElement('div');d.className='toast';d.textContent=t;$('#toastStack').append(d);setTimeout(()=>d.remove(),2800)}
function togglePanel(name){if(panel===name){closePanel();return}panel=name;$('#panel').classList.remove('hidden');renderPanel(name)}function closePanel(){panel=null;$('#panel').classList.add('hidden')}
function shell(title,sub,tabs,body){return `<div class="panel-inner"><aside class="panel-side"><h2>${title}</h2><p>${sub}</p><div class="panel-tabs">${tabs.map((x,i)=>`<button class="${i?'':'active'}">${x}</button>`).join('')}</div></aside><article class="panel-main">${body}</article></div>`}
function renderPanel(name){let c=$('#panelContent');if(name==='inventory')c.innerHTML=shell('Satchel','Everything carried has weight and purpose.',['EQUIPMENT','LOADOUTS','ATTRIBUTES'],inventoryHTML());if(name==='forge')c.innerHTML=shell('The Forge','Shape the world from what you harvest.',['ALL RECIPES','REFINING','WEAPONS','ARMOR'],forgeHTML());if(name==='mastery')c.innerHTML=shell('Thread of Fate','Your actions decide what you become.',['CONSTELLATION','COMBAT','CRAFT','GATHER'],masteryHTML());if(name==='factions')c.innerHTML=shell('Divine Oaths','Serve a pantheon. Earn favor. Change the age.',['PANTHEONS','CAMPAIGN','REWARDS'],factionsHTML());if(name==='guild')c.innerHTML=shell('Warbands','Build a hall, claim relics, write a shared legend.',['MY WARBAND','FINDER','TERRITORIES'],guildHTML());if(name==='codex')c.innerHTML=shell('Codex','The first record of Zion.',['VISION','CONTROLS','ROADMAP'],`<h2>ASHES OF THE FIRST GODS</h2><p>Zion is a mythological sandbox action RPG. Your equipment defines your abilities; what you repeatedly do becomes your mastery. Gather, refine, forge, fight, swear an oath, and eventually build a warband stronghold.</p><h2>Playable now</h2><p>Gathering · combat · ability cooldowns · enemy drops · inventory · refining · crafting · experience · mastery · factions · guild founding · quest threads · persistence-ready architecture.</p>`);bindPanel(name)}
function inventoryHTML(){let slots=Object.entries(state.inv).filter(([,v])=>v>0).map(([k,v])=>`<div class="slot rarity-${items[k]?.rarity||1}" data-item="${k}"><span class="item-icon">${items[k]?.icon||'?'}</span><small>${items[k]?.name||k}</small><b>${v}</b></div>`).join('');return `<h2>Wayfarer's Kit</h2><div class="inventory-layout"><div class="paperdoll"><div class="doll">𐀀</div><div class="equip weapon">†</div><div class="equip head">⌃</div><div class="equip chest">♢</div><div class="equip feet">⌄</div><div class="equip offhand">${state.inv.buckler?'◉':'·'}</div></div><div><div class="bag-grid">${slots}${'<div class="slot"></div>'.repeat(Math.max(0,24-Object.keys(state.inv).length))}</div><h3>Combat attributes</h3><div class="stat-row"><span>Item Power</span><b>${142+state.level*8}</b></div><div class="stat-row"><span>Damage</span><b>${18+Math.floor(state.mastery.combat/20)}</b></div><div class="stat-row"><span>Gathering Yield</span><b>+${Math.floor(state.mastery.gather/25)}%</b></div></div></div>`}
function forgeHTML(){return `<h2>Known Recipes</h2><p>Resources become legacy. Every craft advances your Making mastery.</p><div class="recipe-grid">${recipes.map(r=>{let can=!r.locked&&Object.entries(r.cost).every(([k,v])=>state.inv[k]>=v);return `<div class="recipe ${can?'can':''}"><div class="recipe-icon">${r.icon}</div><small>${r.kind}</small><h3>${r.name}</h3><div class="recipe-cost">${Object.entries(r.cost).map(([k,v])=>`${items[k].icon} ${v} ${items[k].name}`).join(' · ')}</div><button data-craft="${r.id}" ${can?'':'disabled'}>${r.locked?'REQUIRES MAKING II':'FORGE'}</button></div>`}).join('')}</div>`}
function masteryHTML(){let m=state.mastery;return `<h2>The Constellation</h2><p>No fixed class. The path remembers your deeds.</p><div class="mastery-board"><div class="node center done"><div><strong>✦</strong>Wayfarer</div></div><div class="node n1 ${m.combat>=50?'done':''}"><div><strong>†</strong>Blade Lore<div class="meter"><i style="width:${Math.min(100,m.combat*2)}%"></i></div>${m.combat}/50</div></div><div class="node n2 ${m.gather>=50?'done':''}"><div><strong>♣</strong>Harvesting<div class="meter"><i style="width:${Math.min(100,m.gather*2)}%"></i></div>${m.gather}/50</div></div><div class="node n3 ${m.craft>=50?'done':''}"><div><strong>⚒</strong>Making<div class="meter"><i style="width:${Math.min(100,m.craft*2)}%"></i></div>${m.craft}/50</div></div><div class="node n4"><div><strong>⚑</strong>Oathbound<div class="meter"><i style="width:${state.favor*10}%"></i></div>${state.favor}/10</div></div></div>`}
function factionsHTML(){let fs=[['Olympian Accord','Sun-bright conquerors of law and glory.','☀'],['House of Anubis','Keepers of passage, memory, and judgment.','𓁢'],['The Morrígan Host','War-crows who prize daring and prophecy.','♠']];return `<h2>Choose an Oath</h2><p>Faction choice is permanent for this prototype save.</p><div class="faction-grid">${fs.map(([n,d,i])=>`<div class="faction-card"><div class="recipe-icon">${i}</div><h3>${n}</h3><p>${d}</p><button class="primary-btn" data-faction="${n}" ${state.faction?'disabled':''}>${state.faction===n?'OATH SWORN':state.faction?'BOUND ELSEWHERE':'SWEAR OATH'}</button></div>`).join('')}</div>`}
function guildHTML(){return `<h2>${state.guild||'No Warband'}</h2>${state.guild?`<p>Your hall is newly founded. Recruit allies and gather 5,000 drachma to claim your first relic-site.</p><div class="stat-row"><span>Members</span><b>1 / 20</b></div><div class="stat-row"><span>Warband Renown</span><b>0</b></div><div class="stat-row"><span>Treasury</span><b>${state.silver} ◈</b></div>`:`<p>A warband is a player-made guild. Founding one costs 100 drachma.</p><input id="guildName" maxlength="22" placeholder="WARBAND NAME" style="width:100%;padding:12px;background:#100c14;border:1px solid #59435b;color:#eee"><button class="primary-btn" id="foundGuild" ${state.silver<100?'disabled':''}>FOUND FOR 100 ◈</button>`}`}
function bindPanel(name){$$('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));$$('[data-faction]').forEach(b=>b.onclick=()=>{state.faction=b.dataset.faction;state.favor+=2;toast('OATH SWORN · '+state.faction.toUpperCase());renderPanel('factions')});let fg=$('#foundGuild');if(fg)fg.onclick=()=>{let n=$('#guildName').value.trim();if(n&&state.silver>=100){state.silver-=100;state.guild=n;toast('WARBAND FOUNDED · '+n.toUpperCase());renderPanel('guild')}}}
function craft(id){let r=recipes.find(x=>x.id===id);if(!r||Object.entries(r.cost).some(([k,v])=>state.inv[k]<v))return;for(let [k,v] of Object.entries(r.cost))state.inv[k]-=v;state.inv[id]=(state.inv[id]||0)+r.out;state.mastery.craft+=12;gainXp(18);toast(`${r.name.toUpperCase()} FORGED · +18 RENOWN`);checkQuest();renderPanel('forge')}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
