import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
import {createPalette,createWayfarer,createEnemy,createGloamwood,createResourceNode,groundHeight,animateHumanoid} from './gloamwood-visuals.js';
import {createGraphicsController,GRAPHICS_PRESETS} from './graphics-settings.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#world'), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const scene=new THREE.Scene(); scene.background=new THREE.Color(0x17242b);scene.fog=new THREE.FogExp2(0x29404a,.018);
const camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,500);camera.position.set(0,4,8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight,false);renderer.info.autoReset=false;renderer.shadowMap.enabled=false;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.5;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.35,.65,.25);composer.addPass(bloom);
let applyGraphicsWorkload=()=>{};
const graphics=createGraphicsController({renderer,composer,bloom,canvas,onChange:()=>applyGraphicsWorkload()});
const hemi=new THREE.HemisphereLight(0x89a9bd,0x241716,1.25);scene.add(hemi);const moon=new THREE.DirectionalLight(0xffc77d,5.2);moon.position.set(-16,24,8);moon.castShadow=false;scene.add(moon);
const mats={ground:new THREE.MeshStandardMaterial({color:0x45404a,roughness:.95}),stone:new THREE.MeshStandardMaterial({color:0x62566b,roughness:.82}),bronze:new THREE.MeshStandardMaterial({color:0x856342,metalness:.72,roughness:.42}),wood:new THREE.MeshStandardMaterial({color:0x4e342b,roughness:1}),leaf:new THREE.MeshStandardMaterial({color:0x385848,roughness:1}),enemy:new THREE.MeshStandardMaterial({color:0x67334c,roughness:.65}),skin:new THREE.MeshStandardMaterial({color:0xd2a082,roughness:.8}),cloth:new THREE.MeshStandardMaterial({color:0x642c4d,roughness:.8}),black:new THREE.MeshStandardMaterial({color:0x111019,metalness:.75,roughness:.25}),violet:new THREE.MeshStandardMaterial({color:0x421369,emissive:0x9d20ff,emissiveIntensity:6,metalness:.55,roughness:.22}),fire:new THREE.MeshStandardMaterial({color:0xff7a25,emissive:0xff2600,emissiveIntensity:8}),teal:new THREE.MeshStandardMaterial({color:0x108d91,emissive:0x00f1df,emissiveIntensity:5})};
const state={level:1,xp:0,xpNext:100,hp:120,maxHp:120,energy:100,maxEnergy:100,silver:180,favor:0,keys:{},quest:0,faction:null,guild:null,mastery:{combat:8,gather:0,craft:0},cool:{cleave:0,dash:0,mend:0},inv:{wood:0,ore:0,hide:0,herb:1,bronze:0,plank:0,sword:1,buckler:0,potion:2},nodes:[],enemies:[],particles:[],orbs:[],drops:[],target:null,locked:null,attacking:0,dead:false};
const cameraRig={yaw:0,pitch:.22,distance:7.5,first:false,drag:false,shake:0};
const items={wood:{name:'Olivewood',icon:'♣',rarity:1},ore:{name:'Bronze Ore',icon:'◆',rarity:1},hide:{name:'Boar Hide',icon:'◒',rarity:1},herb:{name:'Moly Herb',icon:'❧',rarity:2},bronze:{name:'Bronze Ingot',icon:'▰',rarity:2},plank:{name:'Olive Plank',icon:'▥',rarity:2},sword:{name:'Voidfire Xiphos',icon:'†',rarity:3},buckler:{name:'Gorgon Buckler',icon:'◉',rarity:3},potion:{name:'Ambrosia',icon:'⚱',rarity:2}};
const recipes=[{id:'plank',name:'Olive Plank',icon:'▥',cost:{wood:2},out:1,kind:'Refine'},{id:'bronze',name:'Bronze Ingot',icon:'▰',cost:{ore:2},out:1,kind:'Refine'},{id:'sword',name:'Voidfire Xiphos',icon:'†',cost:{bronze:3,wood:1},out:1,kind:'Weapon'},{id:'buckler',name:'Gorgon Buckler',icon:'◉',cost:{bronze:2,wood:2},out:1,kind:'Off-hand'},{id:'potion',name:'Ambrosia',icon:'⚱',cost:{herb:2},out:2,kind:'Consumable'},{id:'spear',name:'Sunscar Spear',icon:'⚚',cost:{plank:3,bronze:2},out:1,kind:'Weapon',locked:true}];
function mesh(g,m,cast=true){const o=new THREE.Mesh(g,m);o.castShadow=cast;o.receiveShadow=true;return o}
const legacyRoot=new THREE.Group();scene.add(legacyRoot);const ground=mesh(new THREE.CylinderGeometry(39,43,2,10),mats.ground,false);ground.position.y=-1.2;legacyRoot.add(ground);
for(let i=0;i<90;i++){const s=mesh(new THREE.DodecahedronGeometry(.25+Math.random()*.5,0),i%8?mats.stone:mats.bronze,false);const a=Math.random()*Math.PI*2,r=5+Math.random()*37;s.position.set(Math.cos(a)*r,-.05,Math.sin(a)*r);s.scale.y=.3;s.rotation.y=Math.random()*6;legacyRoot.add(s)}
function makeShrine(){const g=new THREE.Group();for(let i=0;i<8;i++){const a=i/8*Math.PI*2,p=mesh(new THREE.CylinderGeometry(.45,.62,5,6),mats.stone);p.position.set(Math.cos(a)*5,2.4,Math.sin(a)*5);p.rotation.z=(Math.random()-.5)*.13;g.add(p);const rune=mesh(new THREE.TorusGeometry(.48,.075,5,12),i%2?mats.violet:mats.teal,false);rune.rotation.x=Math.PI/2;rune.position.copy(p.position);rune.position.y=3.2;g.add(rune)}const altar=mesh(new THREE.CylinderGeometry(2.3,2.8,.8,8),mats.black);altar.position.y=.15;g.add(altar);const flame=mesh(new THREE.OctahedronGeometry(.72,0),mats.fire,false);flame.name='altarFlame';flame.position.y=1.5;g.add(flame);const light=new THREE.PointLight(0xff3c12,18,12,2);light.position.y=2;g.add(light);legacyRoot.add(g)}makeShrine();
function makePlayer(){const g=new THREE.Group();g.name='player';const torso=mesh(new THREE.CapsuleGeometry(.46,1.05,4,7),mats.cloth);torso.position.y=1.35;g.add(torso);const head=mesh(new THREE.IcosahedronGeometry(.4,1),mats.skin);head.position.y=2.45;g.add(head);const skirt=mesh(new THREE.ConeGeometry(.68,1.2,6),mats.black);skirt.position.y=.55;g.add(skirt);const shoulder=mesh(new THREE.BoxGeometry(1.45,.25,.5),mats.bronze);shoulder.position.y=1.85;g.add(shoulder);const weapon=new THREE.Group();weapon.name='weapon';const grip=mesh(new THREE.CylinderGeometry(.07,.09,1.1,6),mats.black);grip.rotation.z=Math.PI/2;weapon.add(grip);const blade=mesh(new THREE.BoxGeometry(2.2,.22,.12),mats.violet);blade.position.x=1.35;weapon.add(blade);for(let i=0;i<6;i++){const rune=mesh(new THREE.BoxGeometry(.16,.03,.14),i%2?mats.fire:mats.teal,false);rune.position.set(.55+i*.31,.13,.01);weapon.add(rune)}const guard=mesh(new THREE.BoxGeometry(.14,.85,.16),mats.bronze);guard.position.x=.25;weapon.add(guard);weapon.position.set(.7,1.3,0);weapon.rotation.z=-.45;g.add(weapon);const aura=mesh(new THREE.TorusGeometry(1,.045,5,32),mats.violet,false);aura.rotation.x=Math.PI/2;aura.position.y=.08;aura.name='aura';g.add(aura);legacyRoot.add(g);return g}const player=makePlayer();
function addTree(x,z){const g=new THREE.Group(),tr=mesh(new THREE.CylinderGeometry(.22,.38,2.7,6),mats.wood);tr.position.y=1.25;g.add(tr);for(let i=0;i<3;i++){const c=mesh(new THREE.IcosahedronGeometry(.9-i*.12,0),mats.leaf);c.position.set((i-1)*.42,2.5+(i%2)*.35,(i%2-.5)*.35);g.add(c)}g.position.set(x,0,z);g.userData={type:'wood',alive:true};scene.add(g);state.nodes.push(g)}
function addOre(x,z){const g=new THREE.Group();for(let i=0;i<4;i++){const c=mesh(new THREE.OctahedronGeometry(.42+Math.random()*.28,0),i===0?mats.teal:mats.bronze);c.scale.y=1.5;c.position.set((i-1.5)*.38,.45,Math.random()*.35);g.add(c)}g.position.set(x,0,z);g.userData={type:'ore',alive:true};scene.add(g);state.nodes.push(g)}
function addHerb(x,z){const g=new THREE.Group();for(let i=0;i<5;i++){const p=mesh(new THREE.OctahedronGeometry(.18,0),mats.fire,false);p.position.set(Math.cos(i*1.26)*.3,.25+Math.random()*.25,Math.sin(i*1.26)*.3);g.add(p)}g.position.set(x,0,z);g.userData={type:'herb',alive:true};scene.add(g);state.nodes.push(g)}
for(let i=0;i<32;i++){const a=Math.random()*Math.PI*2,r=8+Math.random()*29;(i%6===0?addHerb:i%3===0?addOre:addTree)(Math.cos(a)*r,Math.sin(a)*r)}
// Hand-authored silhouettes: the world is staged as recognizable destinations, not an empty arena.
const worldFx=new THREE.Group();scene.add(worldFx);
function addRock(x,z,s=1,material=mats.stone){const r=mesh(new THREE.DodecahedronGeometry(s,0),material);r.position.set(x,s*.45,z);r.scale.set(1,.8+Math.random()*.8,.7);r.rotation.set(Math.random()*.3,Math.random()*6,Math.random()*.25);worldFx.add(r);return r}
function addPine(x,z,s=1){const g=new THREE.Group(),tr=mesh(new THREE.CylinderGeometry(.18*s,.3*s,2.8*s,7),mats.wood);tr.position.y=1.35*s;g.add(tr);for(let i=0;i<4;i++){const c=mesh(new THREE.ConeGeometry((1.4-i*.18)*s,2.2*s,7),mats.leaf);c.position.y=(2.1+i*.65)*s;c.rotation.y=i*.8;g.add(c)}g.position.set(x,0,z);g.userData.sway=Math.random()*6;worldFx.add(g);return g}
function addRuin(x,z,rot=0){const g=new THREE.Group();for(const side of[-1,1]){const p=mesh(new THREE.BoxGeometry(1.2,6,1.2),mats.stone);p.position.set(side*2.4,3,0);p.rotation.z=side*.08;g.add(p)}const lintel=mesh(new THREE.BoxGeometry(6,1.1,1.3),mats.stone);lintel.position.y=6;lintel.rotation.z=-.04;g.add(lintel);const rune=mesh(new THREE.TorusGeometry(1.25,.12,6,18),mats.teal,false);rune.position.set(0,4,0);g.add(rune);g.position.set(x,0,z);g.rotation.y=rot;worldFx.add(g)}
function addCamp(x,z){const g=new THREE.Group();for(let i=0;i<3;i++){const tent=mesh(new THREE.ConeGeometry(1.8,2.5,4),i===0?mats.cloth:mats.black);tent.position.set((i-1)*3,1.2,(i%2)*2);tent.rotation.y=Math.PI/4;g.add(tent)}const fire=mesh(new THREE.OctahedronGeometry(.4),mats.fire,false);fire.position.y=.5;fire.name='campfire';g.add(fire);const l=new THREE.PointLight(0xff5c22,15,11,2);l.position.y=1;g.add(l);g.position.set(x,0,z);worldFx.add(g)}
function addBridge(){for(let i=-5;i<=5;i++){const plank=mesh(new THREE.BoxGeometry(2.7,.25,1.15),mats.wood);plank.position.set(18,.6,i*1.05);plank.rotation.z=Math.sin(i)*.025;worldFx.add(plank)}for(const x of[16.5,19.5]){const rail=mesh(new THREE.CylinderGeometry(.09,.12,12,6),mats.wood);rail.rotation.x=Math.PI/2;rail.position.set(x,1.5,0);worldFx.add(rail)}}
addRuin(-18,-18,.4);addRuin(24,17,-.7);addCamp(-22,15);addBridge();
for(let i=0;i<48;i++){const a=i/48*Math.PI*2,r=27+(i%5)*2;addPine(Math.cos(a)*r,Math.sin(a)*r,.75+(i%4)*.15)}
for(let i=0;i<65;i++){const a=Math.random()*6.28,r=5+Math.random()*32;const stem=mesh(new THREE.ConeGeometry(.035,.35,4),i%7?mats.leaf:mats.fire,false);stem.position.set(Math.cos(a)*r,.17,Math.sin(a)*r);stem.rotation.z=(Math.random()-.5)*.4;worldFx.add(stem)}
for(let i=0;i<20;i++)addRock(-30+Math.random()*14,-5+Math.random()*18,.6+Math.random()*1.5);
const river=mesh(new THREE.PlaneGeometry(5,86,1,1),new THREE.MeshStandardMaterial({color:0x176f7b,emissive:0x083b48,emissiveIntensity:.7,metalness:.15,roughness:.18,transparent:true,opacity:.9}),false);river.rotation.x=-Math.PI/2;river.position.set(18,.03,0);worldFx.add(river);
const falls=mesh(new THREE.PlaneGeometry(5,10),river.material,false);falls.position.set(18,5,-40);worldFx.add(falls);const fallsLight=new THREE.PointLight(0x56dbea,6,18);fallsLight.position.set(18,4,-36);worldFx.add(fallsLight);
const pollen=new THREE.Points(new THREE.BufferGeometry(),new THREE.PointsMaterial({color:0xffd88a,size:.07,transparent:true,opacity:.75}));const pp=[];for(let i=0;i<240;i++)pp.push((Math.random()-.5)*76,Math.random()*8,(Math.random()-.5)*76);pollen.geometry.setAttribute('position',new THREE.Float32BufferAttribute(pp,3));worldFx.add(pollen);
function spawnEnemy(){const g=new THREE.Group(),body=mesh(new THREE.ConeGeometry(.72,2.3,5),mats.enemy);body.position.y=1.1;g.add(body);const mask=mesh(new THREE.IcosahedronGeometry(.47,0),mats.black);mask.position.y=2.3;g.add(mask);const eye=mesh(new THREE.BoxGeometry(.52,.08,.5),mats.fire,false);eye.position.set(0,2.34,.22);g.add(eye);const ring=mesh(new THREE.TorusGeometry(.85,.055,4,20),mats.fire,false);ring.rotation.x=Math.PI/2;ring.position.y=.08;g.add(ring);const a=Math.random()*Math.PI*2,r=15+Math.random()*19;g.position.set(Math.cos(a)*r,0,Math.sin(a)*r);g.userData={hp:55,maxHp:55,attack:0,dead:false};scene.add(g);state.enemies.push(g)}for(let i=0;i<9;i++)spawnEnemy();
const boss=state.enemies[0];boss.scale.setScalar(1.75);boss.userData.hp=boss.userData.maxHp=180;boss.userData.boss=true;boss.position.set(-18,0,-15);
// Replace the legacy prototype art with the authored Ruins of Gloamwood slice.
const art=createPalette(THREE);bloom.strength=.34;bloom.radius=.28;bloom.threshold=.86;bloom.enabled=false;renderer.toneMappingExposure=1.26;scene.fog.density=.011;
scene.remove(legacyRoot);scene.add(player);for(const n of state.nodes)scene.remove(n);for(const e of state.enemies)scene.remove(e);state.nodes.length=0;state.enemies.length=0;worldFx.clear();
const slice=createGloamwood(THREE,art);worldFx.add(slice.world);const activePollen=slice.pollen;
function batchStaticWorld(){slice.world.updateMatrixWorld(true);const groups=new Map(),remove=[];slice.world.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||o.material.transparent||o.material.emissive?.getHex()>0||o.name==='sculptedTerrain')return;const geo=o.geometry.clone();geo.applyMatrix4(o.matrixWorld);const normalized=geo.index?geo.toNonIndexed():geo;(groups.get(o.material.uuid)||groups.set(o.material.uuid,{material:o.material,geos:[]}).get(o.material.uuid)).geos.push(normalized);remove.push(o)});for(const o of remove)o.parent?.remove(o);for(const {material,geos} of groups.values()){if(!geos.length)continue;const merged=mergeGeometries(geos,false);if(!merged)continue;const m=mesh(merged,material,false);m.receiveShadow=true;slice.world.add(m)}slice.world.traverse(o=>{if(o.isMesh)o.castShadow=false})}batchStaticWorld();
const heroArt=createWayfarer(THREE,art);player.clear();while(heroArt.children.length)player.add(heroArt.children[0]);player.userData=heroArt.userData;player.position.set(0,groundHeight(0,-31),-31);function limitActorShadows(a){a.traverse(o=>{if(o.isMesh)o.castShadow=false})}limitActorShadows(player);
scene.add(camera);camera.near=.07;camera.updateProjectionMatrix();const fpRig=new THREE.Group();fpRig.name='firstPersonArms';const fpSword=player.userData.rig.sword.clone(true);fpSword.position.set(.28,-.3,-1.18);fpSword.rotation.set(-.05,-.28,-.72);fpSword.scale.setScalar(.42);fpRig.add(fpSword);for(const side of[-1,1]){const sleeve=mesh(new THREE.CylinderGeometry(.06,.085,.48,7),art.cloth,false);sleeve.rotation.z=-.24*side;sleeve.rotation.x=-1.25;sleeve.position.set(side*.2,-.34,-.72);fpRig.add(sleeve);const glove=mesh(new THREE.SphereGeometry(.07,7,5),art.leather,false);glove.position.set(side*.27,-.39,-.93);glove.scale.set(.75,1.05,.75);fpRig.add(glove)}fpRig.visible=false;camera.add(fpRig);
function batchNode(n){n.updateMatrixWorld(true);const groups=new Map();for(const o of [...n.children]){if(!o.isMesh)continue;const geo=o.geometry.clone();geo.applyMatrix4(o.matrix);const normalized=geo.index?geo.toNonIndexed():geo;(groups.get(o.material.uuid)||groups.set(o.material.uuid,{material:o.material,geos:[]}).get(o.material.uuid)).geos.push(normalized);n.remove(o)}for(const {material,geos} of groups.values()){const merged=mergeGeometries(geos,false);if(merged)n.add(mesh(merged,material,false))}}
for(const [type,x,z] of[['wood',-6,-25],['wood',7,-20],['wood',-11,4],['ore',6,-7],['ore',8,7],['ore',-6,19],['herb',-4,-17],['herb',5,11]]){const n=createResourceNode(THREE,art,type,x,z);batchNode(n);scene.add(n);state.nodes.push(n)}
const enemySpawns=[['raider',-5,-3],['raider',7,3],['raider',-9,14],['raider',-5,17],['guardian',5,12],['guardian',-6,25],['guardian',7,27],['boss',0,34]];
function spawnSliceEnemy(kind='raider',x=4,z=8){const e=createEnemy(THREE,art,kind);e.position.set(x,groundHeight(x,z),z);const hp=kind==='boss'?260:kind==='guardian'?90:62;e.userData={...e.userData,hp,maxHp:hp,attack:0,dead:false,boss:kind==='boss',hitReact:0,deathAnim:0,attackAnim:0,lastX:x,lastZ:z};limitActorShadows(e);scene.add(e);state.enemies.push(e);return e}
for(const [kind,x,z] of enemySpawns)spawnSliceEnemy(kind,x,z);spawnEnemy=function(){const kind=Math.random()<.35?'guardian':'raider',x=(Math.random()-.5)*16,z=4+Math.random()*22;return spawnSliceEnemy(kind,x,z)};
const contactShadow=new THREE.InstancedMesh(new THREE.CircleGeometry(1,18),new THREE.MeshBasicMaterial({color:0x050708,transparent:true,opacity:.34,depthWrite:false}),12);contactShadow.rotation.x=-Math.PI/2;contactShadow.frustumCulled=false;scene.add(contactShadow);const shadowDummy=new THREE.Object3D();
slice.world.traverse(o=>{if(o.isInstancedMesh)o.userData.fullCount=o.count});
applyGraphicsWorkload=()=>{const q=graphics.effects;slice.world.traverse(o=>{if(o.isInstancedMesh&&o.userData.fullCount)o.count=Math.max(1,Math.round(o.userData.fullCount*q.foliage))});scene.traverse(o=>{if(o.isPointLight)o.visible=q.extraLights});};applyGraphicsWorkload();
const sparkCapacity=72,sparkInstances=new THREE.InstancedMesh(new THREE.TetrahedronGeometry(.075,0),new THREE.MeshBasicMaterial({vertexColors:true}),sparkCapacity),sparkPool=[],sparkDummy=new THREE.Object3D(),sparkColor=new THREE.Color();sparkInstances.frustumCulled=false;sparkInstances.instanceMatrix.setUsage(THREE.DynamicDrawUsage);scene.add(sparkInstances);for(let i=0;i<sparkCapacity;i++)sparkPool.push({position:new THREE.Vector3(),v:new THREE.Vector3(),life:0,scale:0,color:new THREE.Color()});function burst(pos,color=0x9f4438,count=12){count=Math.min(count,graphics.effects.particles-state.particles.length,sparkPool.length);for(let i=0;i<count;i++){const p=sparkPool.pop();p.position.copy(pos);p.position.y+=1.2;p.v.set((Math.random()-.5)*5,1.5+Math.random()*3.2,(Math.random()-.5)*5);p.life=.35+Math.random()*.45;p.scale=.65+Math.random()*.7;p.color.setHex(color);state.particles.push(p)}}
let audioCtx,ambienceStarted=false;function tone(freq=180,dur=.08,type='sine',gain=.035,slide=.55){audioCtx??=new AudioContext();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.setValueAtTime(freq,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(35,freq*slide),audioCtx.currentTime+dur);g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function noise(dur=.08,gain=.03,filter=900){audioCtx??=new AudioContext();const length=Math.floor(audioCtx.sampleRate*dur),buf=audioCtx.createBuffer(1,length,audioCtx.sampleRate),d=buf.getChannelData(0);for(let i=0;i<length;i++)d[i]=(Math.random()*2-1)*(1-i/length);const s=audioCtx.createBufferSource(),f=audioCtx.createBiquadFilter(),g=audioCtx.createGain();s.buffer=buf;f.type='lowpass';f.frequency.value=filter;g.gain.value=gain;s.connect(f).connect(g).connect(audioCtx.destination);s.start()}
function sound(name){if(name==='light'){noise(.11,.022,1700);tone(210,.09,'triangle',.018,1.8)}if(name==='heavy'){noise(.2,.045,900);tone(105,.2,'sawtooth',.035,.45)}if(name==='flesh'){noise(.1,.04,520);tone(82,.11,'sine',.025,.6)}if(name==='stone'){noise(.12,.045,1800);tone(155,.13,'square',.018,.72)}if(name==='critical'){noise(.2,.06,2400);tone(95,.22,'sawtooth',.05,.32)}if(name==='death'){tone(120,.38,'sawtooth',.03,.24)}if(name==='loot'){tone(410,.12,'triangle',.025,1.7);setTimeout(()=>tone(680,.18,'sine',.02,1.2),70)}}
function startAmbience(){if(ambienceStarted)return;ambienceStarted=true;audioCtx??=new AudioContext();const loop=()=>{if(!started)return;noise(1.8,.0035,260);if(Math.random()<.45)tone(900+Math.random()*600,.08,'sine',.004,1.15);setTimeout(loop,1400+Math.random()*1800)};loop()}
function spawnXp(pos,total){const count=Math.ceil(total/7);for(let i=0;i<count;i++){const o=mesh(new THREE.IcosahedronGeometry(.11+Math.random()*.055,1),new THREE.MeshBasicMaterial({color:i%4?0x75d8d3:0xe7c36d}),false);o.position.copy(pos).add(new THREE.Vector3(0,1.15,0));o.userData={value:Math.min(7,total-i*7),life:12,v:new THREE.Vector3((Math.random()-.5)*4,2.2+Math.random()*2.2,(Math.random()-.5)*4),born:performance.now(),homing:false};scene.add(o);state.orbs.push(o)}burst(pos,0x7fded4,Math.min(20,count*2))}
function spawnDrop(pos,rare=false){if(!rare&&Math.random()>.35)return;const g=new THREE.Group(),color=rare?0xe28a3c:0x5b8fc2,beam=mesh(new THREE.CylinderGeometry(.025,.12,2.2,8),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.38,depthWrite:false}),false),item=mesh(new THREE.DodecahedronGeometry(.22,0),rare?art.fire:art.magic,false);beam.position.y=1.1;item.position.y=.28;g.add(beam,item);g.position.copy(pos);g.userData={rare,life:16};scene.add(g);state.drops.push(g);loot(rare?'LEGENDARY RELIC REVEALED':'RARE SPOILS REVEALED')}
let started=false,panel=null,last=0;function enter(){if(started)return;started=true;startAmbience();$('#boot').style.opacity=0;setTimeout(()=>$('#boot').remove(),1000);$('#game').classList.remove('hidden');toast('THE RUINS OF GLOAMWOOD');setTimeout(()=>$('.controls-hint')?.classList.add('learned'),11000);requestAnimationFrame(loop)}$('#enterBtn').onclick=enter;$('#boot').onclick=enter;
addEventListener('keydown',e=>{state.keys[e.key.toLowerCase()]=true;const m={i:'inventory',c:'forge',p:'mastery',f:'factions',g:'guild'}[e.key.toLowerCase()];if(m)togglePanel(m);if(e.key==='Escape')closePanel();if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='v'){cameraRig.first=!cameraRig.first;toast(cameraRig.first?'FIRST-PERSON VIEW':'THIRD-PERSON VIEW')}if(e.key.toLowerCase()==='q')toggleLock();if('124'.includes(e.key))useAbility({'1':'cleave','2':'dash','4':'mend'}[e.key])});addEventListener('keyup',e=>state.keys[e.key.toLowerCase()]=false);
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
function tapAction(cx,cy){pointer.set(cx/innerWidth*2-1,-cy/innerHeight*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(state.enemies.filter(x=>!x.userData.dead),true);if(hits.length){let o=hits[0].object;while(o.parent&&!state.enemies.includes(o))o=o.parent;attack(o);return}const plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);const at=new THREE.Vector3();ray.ray.intersectPlane(plane,at);state.target=at}
canvas.addEventListener('contextmenu',e=>e.preventDefault());
/* Unified pointer input.
   Desktop: left-click = act, right-drag = orbit, wheel = zoom (unchanged).
   Touch: tap = act, one-finger drag = orbit, two-finger pinch = zoom. */
const touches=new Map();let touchStart=null,touchDragging=false,pinchDist=0;
canvas.addEventListener('pointerdown',e=>{
  if(e.pointerType==='touch'){
    touches.set(e.pointerId,{x:e.clientX,y:e.clientY});
    if(touches.size===1){touchStart={x:e.clientX,y:e.clientY,t:performance.now()};touchDragging=false;}
    else if(touches.size===2){const p=[...touches.values()];pinchDist=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);touchStart=null;}
    return;
  }
  if(e.button===2){cameraRig.drag=true;return}
  if(e.button===0)tapAction(e.clientX,e.clientY);
});
addEventListener('pointermove',e=>{
  if(e.pointerType==='touch'){
    const rec=touches.get(e.pointerId);if(!rec)return;
    const px=rec.x,py=rec.y;rec.x=e.clientX;rec.y=e.clientY;
    if(touches.size===1&&touchStart){
      if(!touchDragging&&Math.hypot(e.clientX-touchStart.x,e.clientY-touchStart.y)>12)touchDragging=true;
      if(touchDragging){cameraRig.yaw-=(e.clientX-px)*.008;cameraRig.pitch=clamp(cameraRig.pitch-(e.clientY-py)*.005,-.3,.75)}
    }else if(touches.size===2){
      const p=[...touches.values()];const d=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);
      if(pinchDist)cameraRig.distance=clamp(cameraRig.distance+(pinchDist-d)*.03,3.5,12);
      pinchDist=d;
    }
    return;
  }
  if(cameraRig.drag){cameraRig.yaw-=e.movementX*.006;cameraRig.pitch=clamp(cameraRig.pitch-e.movementY*.004,-.3,.75)}
});
addEventListener('pointerup',e=>{
  if(e.pointerType==='touch'){
    touches.delete(e.pointerId);
    if(touchStart&&!touchDragging&&performance.now()-touchStart.t<400)tapAction(e.clientX,e.clientY);
    touchStart=null;if(touches.size<2)pinchDist=0;
    return;
  }
  cameraRig.drag=false;
});
addEventListener('pointercancel',e=>{touches.delete(e.pointerId);touchStart=null;if(touches.size<2)pinchDist=0;});
canvas.addEventListener('wheel',e=>{cameraRig.distance=clamp(cameraRig.distance+Math.sign(e.deltaY)*.8,3.5,12)},{passive:true});
/* Touch HUD + ability-bar buttons reuse the existing keyboard handlers via
   synthetic events, so no game logic changes. */
document.querySelectorAll('[data-vkey],.skill[data-key]').forEach(b=>{
  b.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();
    const k=b.dataset.vkey||b.dataset.key;
    dispatchEvent(new KeyboardEvent('keydown',{key:k}));
    setTimeout(()=>dispatchEvent(new KeyboardEvent('keyup',{key:k})),80);
  });
});
function toggleLock(){if(state.locked){state.locked=null;$('#targetCard').classList.add('hidden');return}state.locked=near(state.enemies.filter(e=>!e.userData.dead),15);if(state.locked){$('#targetCard').classList.remove('hidden');$('#targetName').textContent=state.locked.userData.boss?'THE HOLLOW COLOSSUS':state.locked.userData.kind==='guardian'?'HOLLOW GUARDIAN':'GLOAMWOOD RAIDER';tone(180,.08,'square')}}
function distance(a,b){return Math.hypot(a.position.x-b.position.x,a.position.z-b.position.z)}function near(list,max){let best=null,d=max;for(const o of list){const q=distance(player,o);if(q<d){best=o;d=q}}return best}let lastFoot=0,frameCounter=0,lastMapDraw=0,lastCollision=0,hitStop=0;const tempA=new THREE.Vector3(),tempB=new THREE.Vector3(),tempC=new THREE.Vector3(),cameraCollisionRay=new THREE.Raycaster(),lastSafeCamera=new THREE.Vector3();
function update(dt,t){frameCounter++;let sx=(state.keys.d?1:0)-(state.keys.a?1:0),sz=(state.keys.w?1:0)-(state.keys.s?1:0),dx=0,dz=0;if(sx||sz){const l=Math.hypot(sx,sz);sx/=l;sz/=l;dx=Math.sin(cameraRig.yaw)*sz+Math.cos(cameraRig.yaw)*sx;dz=Math.cos(cameraRig.yaw)*sz-Math.sin(cameraRig.yaw)*sx;state.target=null}else if(state.target){tempA.copy(state.target).sub(player.position).setY(0);if(tempA.lengthSq()>.0625){tempA.normalize();dx=tempA.x;dz=tempA.z}else state.target=null}const moveSpeed=state.keys.shift?8.2:5.6;if(dx||dz){player.position.x=clamp(player.position.x+dx*moveSpeed*dt,-34,34);player.position.z=clamp(player.position.z+dz*moveSpeed*dt,-34,39);const desired=Math.atan2(dx,dz);player.rotation.y+=Math.atan2(Math.sin(desired-player.rotation.y),Math.cos(desired-player.rotation.y))*Math.min(1,dt*12);if(t-lastFoot>(state.keys.shift?280:390)){const wet=Math.abs(player.position.z+13)<3.6;noise(.045,wet?.014:.009,wet?520:1050);lastFoot=t}}player.position.y=groundHeight(player.position.x,player.position.z);animateHumanoid(player,t,dt,(dx||dz)?moveSpeed:0,state.attacking);state.energy=clamp(state.energy+8*dt,0,state.maxEnergy);for(const k in state.cool)state.cool[k]=Math.max(0,state.cool[k]-dt);state.attacking=Math.max(0,state.attacking-dt);fpRig.visible=cameraRig.first;fpRig.rotation.z=state.attacking?Math.sin(state.attacking*8)*.42:Math.sin(t*.0017)*.012;fpRig.position.y=Math.sin(t*.002)*.012;
 const weapon=player.getObjectByName('weapon');if(weapon&&state.attacking)weapon.rotation.y=Math.sin(state.attacking*18)*.08;const flame=scene.getObjectByName('campfire');if(flame){flame.scale.y=1+Math.sin(t*.008)*.22;flame.rotation.y=t*.002}
 for(const e of state.enemies){const d=distance(player,e),nearEnough=d<graphics.effects.viewDistance||state.locked===e;e.visible=nearEnough;if(!nearEnough){if((frameCounter+e.id)%12)continue;e.userData.attack-=dt*12;continue}if(e.userData.dead){e.userData.deathAnim+=dt;e.rotation.z=Math.min(Math.PI*.47,e.userData.deathAnim*2.5);e.scale.multiplyScalar(Math.max(.965,1-dt*.12));continue}e.userData.hitReact=Math.max(0,e.userData.hitReact-dt);e.userData.attackAnim=Math.max(0,e.userData.attackAnim-dt);const oldX=e.position.x,oldZ=e.position.z;if(d<10){tempA.copy(player.position).sub(e.position).setY(0).normalize();if(d>1.75)e.position.addScaledVector(tempA,(e.userData.boss?1.05:1.55)*dt);e.lookAt(player.position.x,e.position.y,player.position.z);e.userData.attack-=dt;if(d<2.15&&e.userData.attack<=0){e.userData.attackAnim=e.userData.boss?1.15:.72;setTimeout(()=>{if(!e.userData.dead&&distance(player,e)<2.7)damagePlayer(e.userData.boss?18:10)},e.userData.boss?520:280);e.userData.attack=e.userData.boss?2.2:1.45}}e.position.y=groundHeight(e.position.x,e.position.z);const es=Math.hypot(e.position.x-oldX,e.position.z-oldZ)/Math.max(dt,.001);animateHumanoid(e,t,dt,es,e.userData.attackAnim);if(e.userData.hitReact)e.userData.rig.root.rotation.x=Math.sin(e.userData.hitReact*18)*.16;const weak=e.userData.rig.weak;if(weak)weak.scale.setScalar(1+Math.sin(t*.004+e.id)*.12)}
 shadowDummy.rotation.set(-Math.PI/2,0,0);const shadowActors=[player,...state.enemies.filter(e=>e.visible&&!e.userData.dead)];for(let i=0;i<12;i++){const a=shadowActors[i];if(a){shadowDummy.position.set(a.position.x,groundHeight(a.position.x,a.position.z)+.035,a.position.z);const s=a.userData.boss?1.7:a===player?.72:.62;shadowDummy.scale.set(s,s,s)}else shadowDummy.scale.setScalar(0);shadowDummy.updateMatrix();contactShadow.setMatrixAt(i,shadowDummy.matrix)}contactShadow.instanceMatrix.needsUpdate=true;
 for(let i=state.particles.length-1;i>=0;i--){const p=state.particles[i];p.life-=dt;p.position.addScaledVector(p.v,dt);p.v.y-=7*dt;p.scale*=.94;if(p.life<=0){state.particles.splice(i,1);sparkPool.push(p)}}for(let i=0;i<sparkCapacity;i++){const p=state.particles[i];if(p){sparkDummy.position.copy(p.position);sparkDummy.scale.setScalar(p.scale);sparkInstances.setColorAt(i,p.color)}else sparkDummy.scale.setScalar(0);sparkDummy.updateMatrix();sparkInstances.setMatrixAt(i,sparkDummy.matrix)}sparkInstances.instanceMatrix.needsUpdate=true;if(sparkInstances.instanceColor)sparkInstances.instanceColor.needsUpdate=true;
 for(const o of [...state.orbs]){o.userData.life-=dt;const age=t-o.userData.born;if(age<520){o.position.addScaledVector(o.userData.v,dt);o.userData.v.y-=7*dt}else{const target=player.position.clone().add(new THREE.Vector3(0,1.2,0)),d=o.position.distanceTo(target);if(d<7){o.userData.homing=true;const pull=target.clone().sub(o.position).normalize();o.userData.v.lerp(pull.multiplyScalar(6.5),dt*5);o.position.addScaledVector(o.userData.v,dt);o.scale.setScalar(clamp(d/2,.2,1))}else{o.position.y=groundHeight(o.position.x,o.position.z)+.55+Math.sin((t+o.id)*.004)*.12}if(state.orbs.length>8){const mate=state.orbs.find(q=>q!==o&&q.position.distanceTo(o.position)<.34);if(mate){o.userData.value+=mate.userData.value;scene.remove(mate);state.orbs.splice(state.orbs.indexOf(mate),1);o.scale.multiplyScalar(1.12)}}if(d<.52){gainXp(o.userData.value);tone(470+Math.min(400,o.userData.value*22),.08,'sine',.018,1.35);$('.player-card')?.classList.add('xp-pulse');setTimeout(()=>$('.player-card')?.classList.remove('xp-pulse'),220);scene.remove(o);state.orbs.splice(state.orbs.indexOf(o),1)}}}
 for(const d of [...state.drops]){d.userData.life-=dt;d.children[1].rotation.y+=dt*1.8;d.children[0].material.opacity=.26+Math.sin(t*.004+d.id)*.1;if(d.position.distanceTo(player.position)<1.15){sound('loot');loot(d.userData.rare?'LEGENDARY RELIC COLLECTED':'RARE SPOILS COLLECTED');scene.remove(d);state.drops.splice(state.drops.indexOf(d),1)}else if(d.userData.life<=0){scene.remove(d);state.drops.splice(state.drops.indexOf(d),1)}}
 activePollen.rotation.y=t*.00002;const pa=activePollen.geometry.attributes.position;for(let i=0;i<pa.count;i++){let y=pa.getY(i)+dt*(.08+(i%5)*.02);if(y>7)y=-1;pa.setY(i,y)}pa.needsUpdate=true;
 if(state.locked&&state.locked.userData.dead)toggleLock();if(state.locked){const v=state.locked.position.clone().sub(player.position);cameraRig.yaw=Math.atan2(v.x,v.z);$('#targetHp').style.width=state.locked.userData.hp/state.locked.userData.maxHp*100+'%'}
 cameraRig.shake=Math.max(0,cameraRig.shake-dt*4);const focus=tempA.copy(player.position);focus.y+=cameraRig.first?2.12:1.6;const dist=cameraRig.first?.06:cameraRig.distance,shoulder=cameraRig.first?0:(state.locked?1.2:.55),cp=tempB.set(Math.sin(cameraRig.yaw)*-dist+Math.cos(cameraRig.yaw)*shoulder,Math.sin(cameraRig.pitch)*dist+2,Math.cos(cameraRig.yaw)*-dist-Math.sin(cameraRig.yaw)*shoulder).add(focus);if(!cameraRig.first&&t-lastCollision>100){cameraCollisionRay.set(focus,tempC.copy(cp).sub(focus).normalize());cameraCollisionRay.near=.25;cameraCollisionRay.far=focus.distanceTo(cp);const obstruction=cameraCollisionRay.intersectObjects(worldFx.children,true).find(h=>h.object!==river&&h.object!==falls&&!h.object.isPoints);if(obstruction)cp.copy(obstruction.point).lerp(focus,.36);lastCollision=t}if(cameraRig.shake)cp.add(tempC.set((Math.random()-.5)*cameraRig.shake,(Math.random()-.5)*cameraRig.shake,(Math.random()-.5)*cameraRig.shake));camera.position.lerp(cp,1-Math.pow(.0001,dt));const look=tempC.set(Math.sin(cameraRig.yaw)*8,Math.sin(cameraRig.pitch)*5,Math.cos(cameraRig.yaw)*8).add(focus);if(state.locked){tempB.copy(state.locked.position);tempB.y+=1.2;look.lerp(tempB,.8)}camera.lookAt(look);player.visible=!cameraRig.first;updateUI();
}
function interact(){const n=near(state.nodes.filter(x=>x.userData.alive),2.5);if(!n)return;player.userData.anim.gather=.8;state.attacking=.65;sound(n.userData.type==='ore'?'stone':'light');setTimeout(()=>{n.userData.alive=false;n.visible=false;state.inv[n.userData.type]++;state.mastery.gather+=8;gainXp(12);loot('+1 '+items[n.userData.type].name);burst(n.position,n.userData.type==='ore'?0xb89a5f:0x668a61,10);setTimeout(()=>{n.visible=true;n.userData.alive=true},12000);checkQuest()},300)}
function attack(e){if(distance(player,e)>2.8){state.target=e.position.clone();return}state.target=null;player.lookAt(e.position.x,player.position.y,e.position.z);state.attacking=.72;sound('light');setTimeout(()=>{if(!e.userData.dead&&distance(player,e)<3.2)hit(e,18)},170)}
function hit(e,n){const critical=Math.random()<.18;n=critical?Math.round(n*1.8):n;e.userData.hp-=n;e.userData.hitReact=.38;hitStop=critical?.085:.045;cameraRig.shake=critical?.24:.1;const impact=tempA.copy(e.position);impact.y+=e.userData.boss?2.2:1.15;burst(impact,critical?0xe8c77d:e.userData.kind==='guardian'||e.userData.kind==='boss'?0xb7c7c0:0x9f4438,critical?18:10);const dust=tempB.copy(e.position);dust.y=groundHeight(dust.x,dust.z);burst(dust,0x6d5b47,critical?7:4);sound(critical?'critical':e.userData.kind==='guardian'||e.userData.kind==='boss'?'stone':'flesh');tempC.copy(e.position).sub(player.position).setY(0).normalize();e.position.addScaledVector(tempC,critical?.55:.18);showDamage(impact,n,critical);if(critical){const f=document.createElement('div');f.className='critical-flash';document.body.append(f);setTimeout(()=>f.remove(),180)}if(e.userData.hp<=0){e.userData.dead=true;e.userData.deathAnim=0;sound('death');spawnXp(e.position,e.userData.boss?84:e.userData.kind==='guardian'?42:28);spawnDrop(e.position,e.userData.boss||Math.random()<.3);state.silver+=15;state.mastery.combat+=10;loot('+ spoils · drachma');setTimeout(()=>{scene.remove(e);state.enemies.splice(state.enemies.indexOf(e),1);spawnEnemy()},4500)}}
function useAbility(id){if(state.cool[id]>0)return;if(id==='cleave'&&state.energy>=20){state.energy-=20;state.cool[id]=3;state.attacking=.8;sound('heavy');setTimeout(()=>{for(const e of state.enemies)if(!e.userData.dead&&distance(player,e)<4.3)hit(e,32);burst(player.position,0x8560a1,16)},230)}if(id==='dash'&&state.energy>=16){state.energy-=16;state.cool[id]=5;player.userData.anim.dodge=.45;noise(.13,.025,1300);tempA.set(0,0,3.7).applyQuaternion(player.quaternion);player.position.add(tempA);player.position.y=groundHeight(player.position.x,player.position.z);burst(player.position,0x729e9b,10)}if(id==='mend'&&state.inv.potion){state.inv.potion--;state.cool[id]=8;state.hp=clamp(state.hp+48,0,state.maxHp);toast('AMBROSIA RESTORES YOU');tone(330,.3,'sine',.025,1.7);burst(player.position,0x70aa72,12)}}
function damagePlayer(n){if(state.dead)return;state.hp-=n;player.userData.anim.hit=.32;cameraRig.shake=.14;noise(.12,.035,650);burst(player.position,0x9d382f,7);if(state.hp<=0){state.dead=true;$('#deathScreen').classList.remove('hidden')}}function respawn(){state.dead=false;state.hp=state.maxHp;player.position.set(0,groundHeight(0,-31),-31);$('#deathScreen').classList.add('hidden');toast('THE FATES REWEAVE YOUR THREAD')}
function gainXp(n){state.xp+=n;while(state.xp>=state.xpNext){state.xp-=state.xpNext;state.level++;state.xpNext=Math.floor(state.xpNext*1.35);state.maxHp+=12;state.hp=state.maxHp;state.favor++;toast(`RENOWN ${state.level} · THE GODS TAKE NOTICE`)}}
function checkQuest(){if(state.quest===0&&state.inv.wood>=3&&state.inv.ore>=2){state.quest=1;state.silver+=75;state.favor++;toast('THREAD COMPLETE · +75 DRACHMA');$('#questTitle').textContent='The First Forging';$('#questText').textContent='Refine an olive plank and a bronze ingot.'}if(state.quest===1&&state.inv.plank&&state.inv.bronze){state.quest=2;toast('NEW PATH · CRAFT A BUCKLER');$('#questTitle').textContent='An Heirloom Reborn';$('#questText').textContent='Craft a Gorgon Buckler at the forge.'}if(state.quest===2&&state.inv.buckler){state.quest=3;state.favor+=3;toast('GORGON OATH EARNED');$('#questTitle').textContent='Beyond the Gloam';$('#questText').textContent='Reach Renown 3 and choose a divine faction.'}}
function updateUI(){const n=near(state.nodes.filter(x=>x.userData.alive),2.5);$('#prompt').classList.toggle('hidden',!n);if(n)$('#prompt span').textContent='Gather '+items[n.userData.type].name;$('#hpBar').style.width=state.hp/state.maxHp*100+'%';$('#energyBar').style.width=state.energy/state.maxEnergy*100+'%';$('#hpText').textContent=`${Math.ceil(state.hp)} / ${state.maxHp}`;$('#energyText').textContent=`${Math.ceil(state.energy)} / ${state.maxEnergy}`;$('#xpBar').style.width=state.xp/state.xpNext*100+'%';$('#levelBadge').textContent=state.level;$('#silver').textContent=state.silver;$('#favor').textContent=state.favor;$$('.skill[data-ability]').forEach(b=>{const c=state.cool[b.dataset.ability],m={cleave:3,dash:5,mend:8};b.querySelector('.cooldown').style.transform=`scaleY(${Math.min(1,c/m[b.dataset.ability])})`});drawMap()}
const map=$('#map'),mctx=map.getContext('2d');function drawMap(){const now=performance.now();if(now-lastMapDraw<200)return;lastMapDraw=now;mctx.fillStyle='#110d19';mctx.fillRect(0,0,150,150);mctx.strokeStyle='#8d6baf';mctx.beginPath();mctx.arc(75,75,62,0,Math.PI*2);mctx.stroke();for(const n of state.nodes){if(!n.userData.alive)continue;mctx.fillStyle=n.userData.type==='ore'?'#8c7956':'#507452';mctx.fillRect(75+n.position.x*1.6,75+n.position.z*1.6,2,2)}mctx.fillStyle='#ffce5c';mctx.beginPath();mctx.arc(75+player.position.x*1.6,75+player.position.z*1.6,3,0,Math.PI*2);mctx.fill()}
function showDamage(pos,n,critical){const screen=pos.clone().project(camera),d=document.createElement('div');d.className='damage-number'+(critical?' critical':'');d.textContent=n;d.style.left=(screen.x*.5+.5)*innerWidth+'px';d.style.top=(-screen.y*.5+.5)*innerHeight+'px';document.body.append(d);setTimeout(()=>d.remove(),720)}function loot(t){const d=document.createElement('div');d.className='loot';d.textContent=t;$('#lootFeed').append(d);setTimeout(()=>d.remove(),3000)}function toast(t){const d=document.createElement('div');d.className='toast';d.textContent=t;$('#toastStack').append(d);setTimeout(()=>d.remove(),2800)}
$$('[data-panel]').forEach(b=>b.onclick=()=>togglePanel(b.dataset.panel));$('#closePanel').onclick=closePanel;$('#respawnBtn').onclick=respawn;function togglePanel(n){if(panel===n){closePanel();return}panel=n;$('#panel').classList.remove('hidden');renderPanel(n)}function closePanel(){panel=null;$('#panel').classList.add('hidden')}
function shell(title,sub,tabs,body){return `<div class="panel-inner"><aside class="panel-side"><h2>${title}</h2><p>${sub}</p><div class="panel-tabs">${tabs.map((x,i)=>`<button class="${i?'':'active'}">${x}</button>`).join('')}</div></aside><article class="panel-main">${body}</article></div>`}
function inventoryHTML(){const slots=Object.entries(state.inv).filter(([,v])=>v>0).map(([k,v])=>`<div class="slot rarity-${items[k]?.rarity||1}"><span class="item-icon">${items[k]?.icon||'?'}</span><small>${items[k]?.name||k}</small><b>${v}</b></div>`).join('');return `<h2>Wayfarer's Kit</h2><div class="inventory-layout"><div class="paperdoll"><div class="doll">𐀀</div><div class="equip weapon">†</div><div class="equip head">⌃</div><div class="equip chest">♢</div><div class="equip feet">⌄</div><div class="equip offhand">${state.inv.buckler?'◉':'·'}</div></div><div><div class="bag-grid">${slots}</div><h3>Combat attributes</h3><div class="stat-row"><span>Relic Power</span><b>${142+state.level*8}</b></div><div class="stat-row"><span>Voidfire Damage</span><b>${18+Math.floor(state.mastery.combat/20)}</b></div><div class="stat-row"><span>Gathering Yield</span><b>+${Math.floor(state.mastery.gather/25)}%</b></div></div></div>`}
function forgeHTML(){return `<h2>Known Recipes</h2><p>Every weapon is melee, ritual, or magical—there are no guns in Zion.</p><div class="recipe-grid">${recipes.map(r=>{const can=!r.locked&&Object.entries(r.cost).every(([k,v])=>state.inv[k]>=v);return `<div class="recipe ${can?'can':''}"><div class="recipe-icon">${r.icon}</div><small>${r.kind}</small><h3>${r.name}</h3><div class="recipe-cost">${Object.entries(r.cost).map(([k,v])=>`${items[k].icon} ${v} ${items[k].name}`).join(' · ')}</div><button data-craft="${r.id}" ${can?'':'disabled'}>${r.locked?'REQUIRES MAKING II':'FORGE'}</button></div>`}).join('')}</div>`}
function masteryHTML(){const m=state.mastery;return `<h2>The Constellation</h2><p>No fixed class. The path remembers your deeds.</p><div class="mastery-board"><div class="node center done"><div><strong>✦</strong>Wayfarer</div></div><div class="node n1"><div><strong>†</strong>Blade Lore<div class="meter"><i style="width:${Math.min(100,m.combat*2)}%"></i></div>${m.combat}/50</div></div><div class="node n2"><div><strong>♣</strong>Harvesting<div class="meter"><i style="width:${Math.min(100,m.gather*2)}%"></i></div>${m.gather}/50</div></div><div class="node n3"><div><strong>⚒</strong>Making<div class="meter"><i style="width:${Math.min(100,m.craft*2)}%"></i></div>${m.craft}/50</div></div><div class="node n4"><div><strong>⚑</strong>Oathbound<div class="meter"><i style="width:${state.favor*10}%"></i></div>${state.favor}/10</div></div></div>`}
function factionsHTML(){const fs=[['Olympian Accord','Sun-bright conquerors of law and glory.','☀'],['House of Anubis','Keepers of passage, memory, and judgment.','𓁢'],['The Morrígan Host','War-crows who prize daring and prophecy.','♠']];return `<h2>Choose an Oath</h2><div class="faction-grid">${fs.map(([n,d,i])=>`<div class="faction-card"><div class="recipe-icon">${i}</div><h3>${n}</h3><p>${d}</p><button class="primary-btn" data-faction="${n}" ${state.faction?'disabled':''}>${state.faction===n?'OATH SWORN':state.faction?'BOUND ELSEWHERE':'SWEAR OATH'}</button></div>`).join('')}</div>`}
function guildHTML(){return `<h2>${state.guild||'No Warband'}</h2>${state.guild?`<p>Your hall is newly founded.</p><div class="stat-row"><span>Members</span><b>1 / 20</b></div>`:`<p>Found a player warband for 100 drachma.</p><input id="guildName" maxlength="22" placeholder="WARBAND NAME" style="width:100%;padding:12px;background:#100c14;border:1px solid #59435b;color:#eee"><button class="primary-btn" id="foundGuild">FOUND FOR 100 ◈</button>`}`}
function graphicsHTML(){const s=graphics.settings,d=graphics.diagnostics(),pct=n=>Math.round(n*100)+'%';return `<h2>Graphics</h2><p>World resolution and workload controls. The interface always remains at browser resolution.</p><div class="preset-grid">${Object.keys(GRAPHICS_PRESETS).map(n=>`<button data-preset="${n}" class="${s.preset===n?'active':''}"><b>${n}</b><small>${n==='Low'?'Reduced foliage, particles, lights and view distance':n==='Medium'?'Balanced laptop workload':'Full foliage, particles, view distance and bloom'}</small></button>`).join('')}<button class="${s.preset==='Custom'?'active':''}" disabled><b>Custom</b><small>Active when individual settings differ.</small></button></div><div class="graphics-controls"><label>Render scale <select id="renderScale">${[.5,.67,.75,.85,1].map(v=>`<option value="${v}" ${s.renderScale===v?'selected':''}>${pct(v)}</option>`).join('')}</select></label><p>Lower render scale improves performance but reduces image sharpness.</p><label class="check"><input id="dynamicResolution" type="checkbox" ${s.dynamicResolution?'checked':''}> Enable dynamic resolution</label><label>Target FPS <select id="dynamicTarget">${[30,45,60].map(v=>`<option ${s.dynamicTargetFps===v?'selected':''}>${v}</option>`).join('')}</select></label><label>Minimum dynamic scale <select id="dynamicMin">${[.5,.67,.75,.85,1].map(v=>`<option value="${v}" ${s.dynamicMinScale===v?'selected':''}>${pct(v)}</option>`).join('')}</select></label><label>Maximum dynamic scale <select id="dynamicMax">${[.67,.75,.85,1].map(v=>`<option value="${v}" ${s.dynamicMaxScale===v?'selected':''}>${pct(v)}</option>`).join('')}</select></label><button class="primary-btn" id="fullscreenBtn">${document.fullscreenElement?'EXIT FULLSCREEN':'FULLSCREEN'}</button></div><h3>Live renderer diagnostics</h3><div class="diagnostics">${Object.entries({Class:d.rendererClass,WebGL:d.webglVersion,Renderer:d.renderer,'Unmasked renderer':d.unmaskedRenderer,Vendor:d.vendor,'Unmasked vendor':d.unmaskedVendor,Viewport:d.viewportResolution,'Canvas display':d.canvasCssResolution,'Drawing buffer':d.drawingBufferResolution,'Device pixel ratio':d.devicePixelRatio,Preset:d.preset,'Manual render scale':pct(d.manualRenderScale),'Dynamic resolution':d.dynamicResolution?'On':'Off','Dynamic multiplier':pct(d.dynamicScale),'Effective scale':pct(d.effectiveScale)}).map(([k,v])=>`<span>${k}</span><b>${v}</b>`).join('')}</div>`}
function renderPanel(n){const c=$('#panelContent');if(n==='inventory')c.innerHTML=shell('Satchel','Everything carried has weight and purpose.',['EQUIPMENT','LOADOUTS','ATTRIBUTES'],inventoryHTML());if(n==='forge')c.innerHTML=shell('The Forge','Shape the world from what you harvest.',['ALL RECIPES','REFINING','WEAPONS','ARMOR'],forgeHTML());if(n==='mastery')c.innerHTML=shell('Thread of Fate','Your actions decide what you become.',['CONSTELLATION','COMBAT','CRAFT','GATHER'],masteryHTML());if(n==='factions')c.innerHTML=shell('Divine Oaths','Serve a pantheon. Change the age.',['PANTHEONS','CAMPAIGN','REWARDS'],factionsHTML());if(n==='guild')c.innerHTML=shell('Warbands','Build a hall and claim relics.',['MY WARBAND','FINDER','TERRITORIES'],guildHTML());if(n==='graphics')c.innerHTML=shell('Display','Crisp by default. Reduced resolution is always explicit.',['GRAPHICS'],graphicsHTML());if(n==='codex')c.innerHTML=shell('Codex','The first record of Zion.',['VISION','CONTROLS','ROADMAP'],`<h2>3D MYTHIC SANDBOX</h2><p>PS2-era silhouettes meet animated emissive relics, neon runes, fire, bloom, sparks, and magical melee combat. No guns.</p>`);bindPanel()}
function bindPanel(){$$('[data-craft]').forEach(b=>b.onclick=()=>craft(b.dataset.craft));$$('[data-faction]').forEach(b=>b.onclick=()=>{state.faction=b.dataset.faction;state.favor+=2;toast('OATH SWORN · '+state.faction.toUpperCase());renderPanel('factions')});$$('[data-preset]').forEach(b=>b.onclick=()=>{graphics.applyPreset(b.dataset.preset);renderPanel('graphics')});const rs=$('#renderScale'),dr=$('#dynamicResolution'),target=$('#dynamicTarget'),dmin=$('#dynamicMin'),dmax=$('#dynamicMax');if(rs)rs.onchange=()=>{graphics.update({renderScale:Number(rs.value)});renderPanel('graphics')};if(dr)dr.onchange=()=>{graphics.update({dynamicResolution:dr.checked});renderPanel('graphics')};if(target)target.onchange=()=>graphics.update({dynamicTargetFps:Number(target.value)});if(dmin)dmin.onchange=()=>{graphics.update({dynamicMinScale:Number(dmin.value)});renderPanel('graphics')};if(dmax)dmax.onchange=()=>{graphics.update({dynamicMaxScale:Number(dmax.value)});renderPanel('graphics')};const full=$('#fullscreenBtn');if(full)full.onclick=async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();graphics.applyResolution();renderPanel('graphics')};const fg=$('#foundGuild');if(fg)fg.onclick=()=>{const n=$('#guildName').value.trim();if(n&&state.silver>=100){state.silver-=100;state.guild=n;toast('WARBAND FOUNDED');renderPanel('guild')}}}
function craft(id){const r=recipes.find(x=>x.id===id);if(!r||Object.entries(r.cost).some(([k,v])=>state.inv[k]<v))return;for(const [k,v] of Object.entries(r.cost))state.inv[k]-=v;state.inv[id]=(state.inv[id]||0)+r.out;state.mastery.craft+=12;gainXp(18);toast(r.name.toUpperCase()+' FORGED');checkQuest();renderPanel('forge')}
let lastDiagnosticUpdate=0,lastDiagnostics=graphics.diagnostics();window.__zion={state,scene,worldFx,player,camera,cameraRig,renderer,composer,graphics,moon,groundHeight,teleport(x,z){player.position.set(x,groundHeight(x,z),z)},setBenchmarkView(){player.position.set(0,groundHeight(0,-18),-18);cameraRig.first=false;cameraRig.yaw=0;cameraRig.pitch=.22;cameraRig.distance=7.5;state.target=null;state.locked=null},spawnXp,spawnDrop,attack,hit};function loop(t){const rawDt=last?(t-last)/1000:0,dt=Math.min(.033,rawDt);last=t;if(hitStop>0)hitStop-=dt;else if(!state.dead)update(dt,t);renderer.info.reset();if(graphics.effects.bloom)composer.render();else renderer.render(scene,camera);graphics.sample(rawDt,t);if(t-lastDiagnosticUpdate>500){lastDiagnostics=graphics.diagnostics();lastDiagnosticUpdate=t;const hud=$('#fpsHud');if(hud)hud.textContent=`${Math.round(lastDiagnostics.measuredFps||0)} fps · ${lastDiagnostics.drawingBufferResolution} · ${lastDiagnostics.preset}${lastDiagnostics.dynamicResolution?` · dyn ${Math.round(lastDiagnostics.dynamicScale*100)}%`:''}`}window.__zion.metrics={calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,particles:state.particles.length,fps:lastDiagnostics.measuredFps,diagnostics:lastDiagnostics};requestAnimationFrame(loop)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();graphics.applyResolution()});addEventListener('fullscreenchange',()=>graphics.applyResolution());
